### ISSUE TITLE
[BUG] Documentation does not tell enough about unity/unity_fixture

### ISSUE THREAD

**Issue by idea--list** [FreeRTOS/iot-reference-esp32c3#18]
**Describe the bug**
Just cloned the repo again to see what has been changed in the past few months. Obviously a qualification test has been added.
However i can not manage to try any demos of the current repo, i always get:
`iot-reference-esp32c3/components/FreeRTOS-Libraries-Integration-Tests/FreeRTOS-Libraries-Integration-Tests/src/pkcs11/core_pkcs11_test.c:43:10: fatal error: unity_fixture.h: No such file or directory`

Even in case i try to build the demos i know from earlier.

**System information**
- Hardware board: [ esp32s3 ]
- IDE used: [ VS Code ]
- Operating System: [ Windows 10x64 ]
- Code version: (run ``git describe --tags`` to find it)
- Project/Demo: [ all affected ]
- If your project is a custom application, please add the relevant code snippet(s) in the section titled `"Code to reproduce bug"`.

**Expected behavior**
I expected a clear documentation and that i can build the repo without any problems just like earlier. However that is not the case. As i never used unity, have no clue what that is, why is that relevant and how to integrate that to this repo.

**Steps to reproduce bug**
      1. Try to build any of the examples on a computer on which unity_fixture.h has not been installed yet.
      2. Try to find out what to do based on readme.md or the getting started guide presuming you have no idea about unity.

**Comment by shubnil** [comment]
Hi, We are looking into the same and will get back soon.

**Comment by paulbartell** [comment]
@idea--list Which version of esp-idf are you using? 

I was just able to build successfully with esp-idf v4.4.3. Can you try with that version? 

We have not yet made the changes necessary to build with esp-idf v5.0.

**Comment by idea--list** [comment]
@paulbartell 
I am using ESP-IDF v4.4.3. I wonder why this happens now. Cloned the repo the way it is advised in the readme.
The method was working some months ago.

**Comment by paulbartell** [comment]
@idea--list : Let's check that you have everything checked out correctly:

From your esp-idf directory in powershell, run the following:
```
git checkout 
git submodule update --init --recursive
install.ps1
export.ps1
```
And from your iot-reference-esp32c3 directory:
```
git checkout main
git pull
idf.py fullclean
idf.py build
```

**Comment by idea--list** [comment]
@paulbartell 
Will try that tomorrow and report my findings. Need to have a sleep now 😪

**Comment by idea--list** [comment]
@paulbartell 
Thanks for the help! That made the trick, now it builds without an error.
